services:
  db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - env_network

volumes:
  postgres_data:

networks:
  env_network:
    driver: bridge
